Add anonymous reporting guidelines. Fixes #16
tc39/code-of-conduct pull request #59
Opened 2023-09-18 21:00 UTC by tabatkins

2023-09-18 21:26 UTC, ljharb approved these changes

2023-09-18 21:27 UTC, mpcsh approved these changes

2023-09-18 22:01 UTC, ctcpip requested changes
thanks for doing this.  we should seek consensus for this at plenary, but I don't think it necessarily needs to also get approval from Ecma, as we are not actually changing the policy.  I will confirm.

2023-09-18 22:02 UTC, ctcpip commented on index.md
> +### Anonymous Reports
```suggestion
### Reporting Anonymously
```

2023-09-19 17:54 UTC, ctcpip approved these changes

2023-09-19 17:54 UTC, merged